# =========================================================
# Netlify Configuration File (netlify.toml)
# This file defines the CI/CD settings for your Angular app.
# =========================================================

[build]
# 1. Installation and Build Command
# This runs the standard Angular production build.
# 'npm install' ensures dependencies are present in the CI environment.
# '-- --configuration=production' forces the production settings (optimization, AOT).
command = "npm install && npm run build --configuration=production"

# 2. Publish Directory (REQUIRED TO UPDATE)
# This path tells Netlify where to find the static files to deploy.
# You MUST update 'your-app-name' to match the actual output path defined
# in your angular.json file's 'outputPath' property.
# Common examples: 'dist/my-cool-app/browser' or just 'dist/my-cool-app'
publish = "dist/tab-wheel" # <-- UPDATE THIS PATH

# 3. Redirects for Single Page Application (SPA) Routing
# This rule is ESSENTIAL for Angular. It ensures that any request not matching a
# static file (e.g., /about or /users/123) is routed back to index.html,
# allowing Angular's client-side router to take over.
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

# 4. Optional: Enable Netlify large media feature if needed
# [build.environment]
#   NETLIFY_USE_ORIGINAL_IMAGE_URL = "true"
